### ISSUE TITLE
Installation fails under pipenv

### ISSUE THREAD

**Issue by FedericoMassaioli** [pfalcon/utemplate#16]
Installation fais with pipenv over Python 3.8 and pip 20.3.1:

```
Installing utemplate...
Error:  An error occurred while installing utemplate!
Error text: Collecting utemplate
  Using cached utemplate-1.4.tar.gz (4.1 kB)

    ERROR: Command errored out with exit status 1:
     command: /Users/federico/.local/share/virtualenvs/notification-consumer-dispatcher-wU5PfN33/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r3/2_zddds10zzdvx9sy_3p2stw0000gn/T/pip-install-2t38l5ez/utemplate_f50c993c62e84c119c9ab07e6441f709/setup.py'"'"'; __file__='"'"'/private/var/folders/r3/2_zddds10zzdvx9sy_3p2stw0000gn/T/pip-install-2t38l5ez/utemplate_f50c993c62e84c119c9ab07e6441f709/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/r3/2_zddds10zzdvx9sy_3p2stw0000gn/T/pip-pip-egg-info-dokffrvc
         cwd: /private/var/folders/r3/2_zddds10zzdvx9sy_3p2stw0000gn/T/pip-install-2t38l5ez/utemplate_f50c993c62e84c119c9ab07e6441f709/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/r3/2_zddds10zzdvx9sy_3p2stw0000gn/T/pip-install-2t38l5ez/utemplate_f50c993c62e84c119c9ab07e6441f709/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in utemplate. Report this to its maintainers.
✘ Installation Failed
```

**Comment by pfalcon** [comment]
Thanks for the report. utemplate is primarily intended to be used with https://github.com/pfalcon/pycopy , and its packages don't require setup.py (and so it's not included, to minimize package size).

utemplate is also fully compatible with CPython, but the way I use it is to clone repository and copy manually as needed.

It would be nice to make PyPI packages installable on both Pycopy and CPython, but so far, I can't get to that, working on many other issues I have in queue...

**Comment by FedericoMassaioli** [comment]
I understand.

Found a workaround installing with:
```
pipenv install -e git+https://github.com/pfalcon/utemplate.git#egg=utemplate
```
